# This is the configuration used to check the rubocop source code.

AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - spec/foodcritic/**

EmptyLines:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets
